// Copyright (c) 2021-2022 Drew Edwards
// This file is part of KanjiSchool under AGPL-3.0.
// Full details: https://github.com/Lemmmy/KanjiSchool/blob/master/LICENSE

// Authentication
export const SET_API_KEY = "SET_API_KEY";
export const SET_USER = "SET_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";

// Sync
export const SET_SUBJECTS_LAST_SYNCED = "SET_SUBJECTS_LAST_SYNCED";
export const SET_SYNCING_SUBJECTS = "SET_SYNCING_SUBJECTS";
export const SET_SYNCING_SUBJECTS_PROGRESS = "SET_SYNCING_SUBJECTS_PROGRESS";
export const SET_SUBJECTS_SYNCED_THIS_SESSION = "SET_SUBJECTS_SYNCED_THIS_SESSION";
export const INIT_SUBJECTS = "INIT_SUBJECTS";

export const SET_ASSIGNMENTS_LAST_SYNCED = "SET_ASSIGNMENTS_LAST_SYNCED";
export const SET_SYNCING_ASSIGNMENTS = "SET_SYNCING_ASSIGNMENTS";
export const SET_SYNCING_ASSIGNMENTS_PROGRESS = "SET_SYNCING_ASSIGNMENTS_PROGRESS";
export const INIT_ASSIGNMENTS = "INIT_ASSIGNMENTS";
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";

export const SET_REVIEW_STATISTICS_LAST_SYNCED = "SET_REVIEW_STATISTICS_LAST_SYNCED";
export const SET_SYNCING_REVIEW_STATISTICS = "SET_SYNCING_REVIEW_STATISTICS";
export const SET_SYNCING_REVIEW_STATISTICS_PROGRESS = "SET_SYNCING_REVIEW_STATISTICS_PROGRESS";
export const INIT_REVIEW_STATISTICS = "INIT_REVIEW_STATISTICS";
export const UPDATE_REVIEW_STATISTIC = "UPDATE_REVIEW_STATISTIC";

export const SET_REVIEWS_LAST_SYNCED = "SET_REVIEWS_LAST_SYNCED";
export const SET_SYNCING_REVIEWS = "SET_SYNCING_REVIEWS";
export const SET_SYNCING_REVIEWS_PROGRESS = "SET_SYNCING_REVIEWS_PROGRESS";
export const SET_STREAK = "SET_STREAK";

export const SET_LEVEL_PROGRESSIONS_LAST_SYNCED = "SET_LEVEL_PROGRESSIONS_LAST_SYNCED";
export const SET_SYNCING_LEVEL_PROGRESSIONS = "SET_SYNCING_LEVEL_PROGRESSIONS";
export const SET_SYNCING_LEVEL_PROGRESSIONS_PROGRESS = "SET_SYNCING_LEVEL_PROGRESSIONS_PROGRESS";
export const INIT_LEVEL_PROGRESSIONS = "INIT_LEVEL_PROGRESSIONS";
export const UPDATE_LEVEL_PROGRESSION = "UPDATE_LEVEL_PROGRESSION";

export const SET_STUDY_MATERIALS_LAST_SYNCED = "SET_STUDY_MATERIALS_LAST_SYNCED";
export const SET_SYNCING_STUDY_MATERIALS = "SET_SYNCING_STUDY_MATERIALS";
export const SET_SYNCING_STUDY_MATERIALS_PROGRESS = "SET_SYNCING_STUDY_MATERIALS_PROGRESS";
export const INIT_STUDY_MATERIALS = "INIT_STUDY_MATERIALS";
export const UPDATE_STUDY_MATERIAL = "UPDATE_STUDY_MATERIAL";

export const SET_PENDING_LESSONS = "SET_PENDING_LESSONS";
export const SET_PENDING_REVIEWS = "SET_PENDING_REVIEWS";
export const SET_NEXT_REVIEWS_AVAILABLE = "SET_NEXT_REVIEWS_AVAILABLE";
export const SET_REVIEW_FORECAST = "SET_REVIEW_FORECAST";

export const IMAGES_SYNCED = "IMAGES_SYNCED";
export const SET_SYNCING_IMAGES = "SET_SYNCING_IMAGES";
export const SET_SYNCING_IMAGES_PROGRESS = "SET_SYNCING_IMAGES_PROGRESS";
export const INIT_IMAGES = "INIT_IMAGES";

export const SET_SYNCING_AUDIO = "SET_SYNCING_AUDIO";
export const SET_SYNCING_AUDIO_PROGRESS = "SET_SYNCING_AUDIO_PROGRESS";
export const INCR_SYNCING_AUDIO_PROGRESS = "INCR_SYNCING_AUDIO_PROGRESS";
export const INCR_SYNCING_AUDIO_QUEUE = "INCR_SYNCING_AUDIO_QUEUE";

export const SET_PROCESSING_QUEUE = "SET_PROCESSING_QUEUE";
export const SET_QUEUE_PROGRESS = "SET_QUEUE_PROGRESS";
export const SET_QUEUE_CONNECTION_ERROR = "SET_QUEUE_CONNECTION_ERROR";
export const INCR_QUEUE_NONCE = "INCR_QUEUE_NONCE";

// Session
export const START_SESSION = "START_SESSION";
export const SESSION_PREV_LESSON = "SESSION_PREV_LESSON";
export const SESSION_NEXT_LESSON = "SESSION_NEXT_LESSON";
export const SESSION_SET_QUESTION = "SESSION_SET_QUESTION";
export const SESSION_SET_INCORRECT_ANSWER = "SESSION_SET_INCORRECT_ANSWER";
export const SESSION_DECR_CHOICE_DELAY = "SESSION_DECR_CHOICE_DELAY";
export const SESSION_ANSWER_QUESTION = "SESSION_ANSWER_QUESTION";
export const SESSION_SKIP_QUESTION_DELAY = "SESSION_SKIP_QUESTION_DELAY";
export const SESSION_SKIP_QUESTION_PUT_END = "SESSION_SKIP_QUESTION_PUT_END";
export const SESSION_SKIP_QUESTION_REMOVE = "SESSION_SKIP_QUESTION_REMOVE";
export const SESSION_SUBMIT_ASSIGNMENT = "SESSION_SUBMIT_ASSIGNMENT";
export const SESSION_WRAP_UP = "SESSION_WRAP_UP";
export const END_SESSION = "END_SESSION";

export const SESSION_SET_RESULTS_VIEWED = "SESSION_SET_RESULTS_VIEWED";

export const STUDY_QUEUE_SET_COLLAPSED = "STUDY_QUEUE_SET_COLLAPSED";
export const STUDY_QUEUE_ADD = "STUDY_QUEUE_ADD";
export const STUDY_QUEUE_REMOVE = "STUDY_QUEUE_REMOVE";
export const STUDY_QUEUE_CLEAR = "STUDY_QUEUE_CLEAR";

// Settings
// ---
export const SET_BOOLEAN_SETTING = "SET_BOOLEAN_SETTING";
export const SET_INTEGER_SETTING = "SET_INTEGER_SETTING";
export const SET_STRING_SETTING = "SET_STRING_SETTING";
export const SET_THEME = "SET_THEME";
export const SET_HOTKEY_HELP_VISIBLE = "SET_HOTKEY_HELP_VISIBLE";

export const SET_PRESETS = "SET_PRESETS";

export const SET_TIP = "SET_TIP";
