// Copyright (c) 2021-2022 Drew Edwards
// This file is part of KanjiSchool under AGPL-3.0.
// Full details: https://github.com/Lemmmy/KanjiSchool/blob/master/LICENSE

export const KANA_MAP: Record<string, string> = {
  // Single vowels
  a: "あ",
  i: "い",
  u: "う",
  e: "え",
  o: "お",

  // K and G
  ka: "か",
  ga: "が",
  ki: "き",
  gi: "ぎ",
  ku: "く",
  gu: "ぐ",
  ke: "け",
  ge: "げ",
  ko: "こ",
  go: "ご",

  // K variants
  ca: "か",
  ci: "き",
  cu: "く",
  ce: "け",
  co: "こ",

  // S and Z, special case shi/si
  sa: "さ",
  za: "ざ",
  shi: "し",
  si: "し",
  ji: "じ",
  zi: "じ",
  su: "す",
  zu: "ず",
  se: "せ",
  ze: "ぜ",
  so: "そ",
  zo: "ぞ",

  // T and D, special cases chi/ti, tsu/tu and the small tsu
  ta: "た",
  da: "だ",
  chi: "ち",
  ti: "ち",
  di: "ぢ",
  tsu: "つ",
  tu: "つ",
  du: "づ",
  te: "て",
  de: "で",
  to: "と",
  do: "ど",

  // Standalone small tsu, when not triggered a a double consonant
  ltu: "っ",
  xtu: "っ",
  ltsu: "っ",

  // N but without the standalone N
  na: "な",
  ni: "に",
  nu: "ぬ",
  ne: "ね",
  no: "の",

  // H, B and P, with special case fu/hu
  ha: "は",
  ba: "ば",
  pa: "ぱ",
  hi: "ひ",
  bi: "び",
  pi: "ぴ",
  fu: "ふ",
  hu: "ふ",
  bu: "ぶ",
  pu: "ぷ",
  he: "へ",
  be: "べ",
  pe: "ぺ",
  ho: "ほ",
  bo: "ぼ",
  po: "ぽ",

  // M
  ma: "ま",
  mi: "み",
  mu: "む",
  me: "め",
  mo: "も",

  // Y with special cases the small ones
  ya: "や",
  yu: "ゆ",
  yo: "よ",

  // Small ya/yu/yo standalone, when not triggered by a contraction like 'kyo'
  xya: "ゃ",
  xyu: "ゅ",
  xyo: "ょ",

  // R
  ra: "ら",
  ri: "り",
  ru: "る",
  re: "れ",
  ro: "ろ",

  // R variants for loan words with L sounds
  la: "ら",
  li: "り",
  lu: "る",
  le: "れ",
  lo: "ろ",

  // W with special case small wa
  // wi and we are not represented here, they are used for digraphs 'ui', 'ue'
  wa: "わ",
  wo: "を",
  lwe: "ゎ",
  xwa: "ゎ",

  // Standalone N
  // This one has some special cases when followed by a non-vowel, such as nk -> んk
  nn: "ん",
  "n ": "ん",
  xn: "ん",

  // Regular ya/yu/yo digraphs, many with variants
  kya: "きゃ",
  kyu: "きゅ",
  kyo: "きょ",
  gya: "ぎゃ",
  gyu: "ぎゅ",
  gyo: "ぎょ",
  qya: "くゃ",
  qyu: "くゅ",
  qyo: "くょ",
  sha: "しゃ",
  shya: "しゃ",
  sya: "しゃ",
  shu: "しゅ",
  shyu: "しゅ",
  syu: "しゅ",
  sho: "しょ",
  shyo: "しょ",
  syo: "しょ",
  zya: "じゃ",
  zyu: "じゅ",
  zyo: "じょ",
  ja: "じゃ",
  ju: "じゅ",
  jo: "じょ",
  jya: "じゃ",
  jyu: "じゅ",
  jyo: "じょ",
  cha: "ちゃ",
  cya: "ちゃ",
  chya: "ちゃ",
  tya: "ちゃ",
  chu: "ちゅ",
  cyu: "ちゅ",
  chyu: "ちゅ",
  tyu: "ちゅ",
  cho: "ちょ",
  cyo: "ちょ",
  chyo: "ちょ",
  tyo: "ちょ",
  dya: "ぢゃ",
  dyu: "ぢゅ",
  dyo: "ぢょ",
  tha: "てゃ",
  thu: "てゅ",
  tho: "てょ",
  dha: "でゃ",
  dhu: "でゅ",
  dho: "でょ",
  nya: "にゃ",
  nyu: "にゅ",
  nyo: "にょ",
  hya: "ひゃ",
  hyu: "ひゅ",
  hyo: "ひょ",
  bya: "びゃ",
  byu: "びゅ",
  byo: "びょ",
  pya: "ぴゃ",
  pyu: "ぴゅ",
  pyo: "ぴょ",
  fya: "ふゃ",
  fyu: "ふゅ",
  fyo: "ふょ",
  mya: "みゃ",
  myu: "みゅ",
  myo: "みょ",
  rya: "りゃ",
  ryu: "りゅ",
  ryo: "りょ",
  lya: "りゃ",
  lyu: "りゅ",
  lyo: "りょ",
  vya: "ゔゃ",
  vyu: "ゔゅ",
  vyo: "ゔょ",

  // A bunch of digraphs that use small a/i/u/e/o vowels
  ye: "いぇ",
  wha: "うぁ",
  whi: "うぃ",
  whe: "うぇ",
  who: "うぉ",
  wi: "うぃ",
  we: "うぇ",
  kyi: "きぃ",
  kye: "きぇ",
  qwa: "くぁ",
  qwi: "くぃ",
  qwu: "くぅ",
  qwe: "くぇ",
  qwo: "くぉ",
  qa: "くぁ",
  qi: "くぃ",
  qe: "くぇ",
  qo: "くぉ",
  kwa: "くぁ",
  qyi: "くぃ",
  qye: "くぇ",
  gyi: "ぎぃ",
  gye: "ぎぇ",
  gwa: "ぐぁ",
  gwi: "ぐぃ",
  gwu: "ぐぅ",
  gwe: "ぐぇ",
  gwo: "ぐぉ",
  syi: "しぃ",
  sye: "しぇ",
  she: "しぇ",
  shye: "しぇ",
  zyi: "じぃ",
  zye: "じぇ",
  je: "じぇ",
  jyi: "じぃ",
  jye: "じぇ",
  swa: "すぁ",
  swi: "すぃ",
  swu: "すぅ",
  swe: "すぇ",
  swo: "すぉ",
  che: "ちぇ",
  cyi: "ちぃ",
  cye: "ちぇ",
  tyi: "ちぃ",
  tye: "ちぇ",
  chye: "ちぇ",
  dyi: "ぢぃ",
  dye: "ぢぇ",
  tsa: "つぁ",
  tsi: "つぃ",
  tse: "つぇ",
  tso: "つぉ",
  thi: "てぃ",
  the: "てぇ",
  twa: "とぁ",
  twi: "とぃ",
  twu: "とぅ",
  twe: "とぇ",
  two: "とぉ",
  dhi: "でぃ",
  dhe: "でぇ",
  dwa: "どぁ",
  dwi: "どぃ",
  dwu: "どぅ",
  dwe: "どぇ",
  dwo: "どぉ",
  nyi: "にぃ",
  nye: "にぇ",
  hyi: "ひぃ",
  hye: "ひぇ",
  fwa: "ふぁ",
  fwi: "ふぃ",
  fwu: "ふぅ",
  fwe: "ふぇ",
  fwo: "ふぉ",
  fa: "ふぁ",
  fi: "ふぃ",
  fe: "ふぇ",
  fo: "ふぉ",
  fyi: "ふぃ",
  fye: "ふぇ",
  byi: "びぃ",
  bye: "びぇ",
  pyi: "ぴぃ",
  pye: "ぴぇ",
  myi: "みぃ",
  mye: "みぇ",
  ryi: "りぃ",
  rye: "りぇ",
  lyi: "りぃ",
  lye: "りぇ",
  ve: "ゔぇ",
  vo: "ゔぉ",
  vyi: "ゔぃ",
  vye: "ゔぇ",
  va: "ゔぁ",
  vi: "ゔぃ",

  // Some misc vowel representations
  yi: "い",
  wu: "う",
  whu: "う",
  xa: "ぁ",
  xi: "ぃ",
  xu: "ぅ",
  xe: "ぇ",
  xo: "ぉ",
  xyi: "ぃ",
  xye: "ぇ",

  // 'u' with dakuten -> vu sound
  vu: "ゔ",

  // Small ka/ke
  lka: "ゕ",
  lke: "ゖ",
  xka: "ゕ",
  xke: "ゖ",
  lca: "ゕ",
  lce: "ゖ",
  xca: "ゕ",
  xce: "ゖ",

  // Vowel doubler '-' -> 'ー'
  "-": "ー",
};

// Add the Katakana characters (for uppercase)
for (const key in KANA_MAP) {
  // KANA_MAP[key.toUpperCase()] = toKatakana(KANA_MAP[key]) || "";
  KANA_MAP[key.toUpperCase()] = KANA_MAP[key] || "";
}
